Development
keygang/yads-bash-software-design pull request #2
Opened 2022-02-15 01:33 UTC by keygang

2022-04-09 18:24 UTC, uncerso requested changes

2022-04-09 18:24 UTC, uncerso commented on src/bash/bash.cpp
> +    std::cout << hint();
`std::cout` -- буферизированный поток. Если хотите быть уверенными, что пользователь увидет сообщение после этой строки, надо использовать либо `std::cout.flush()`, либо `std::cout << std::flush`, либо `std::cout << std::endl`, если нужен ещё перенос на новую строку (как несколькими строками дальше).

2022-04-09 18:24 UTC, uncerso commented on src/bash/bash.cpp
> +    std::getline(std::cin, line);
А если поток уже закрыт? Вы будете вечно в вашем цикле крутиться, получая от `getline` пустую строку. Лёгкий способ это получить: `./build/src/bash <<< 'echo meow'`.

2022-04-09 18:24 UTC, uncerso commented on src/bash/bash.hpp
> + * Класс Bash.
![image](https://user-images.githubusercontent.com/25592720/162577174-7b28f8d8-4e17-4b3b-939e-d4eed22de175.png)

Нет бы написали, что это ваш маленький, но прекрасный интерпретатор шелл, который идёт по стопам баша.

2022-04-09 18:24 UTC, uncerso commented on src/parsing/parser.hpp
> +   * @return              tuple из команды и ее аргументов
Вообще, так как здесь нет подробностей реализации, эти слова декларирует интерфейс, а не его имплементация.

2022-04-09 18:24 UTC, uncerso commented on src/parsing/parse_command_and_arguments.cpp
> +  while (std::isspace(line[first_not_space]) != 0) {
Мм, какая прелесть. Вас, конечно, спасает от out of bound то, что неявно в строке всегда `\0` есть последним элементом. Но лучше так не делать и явно проверять на достижение конца.

К тому же, вы проверяете явно на `!= 0`, хотя это и так произошло бы при приведении `int` к `bool`.

2022-04-09 18:24 UTC, uncerso commented on src/parsing/parse_command_and_arguments.cpp
> +ParseCommandAndArguments::parse(const std::string& line) {
Если функция не помещается на экран -- это плохо спроектированная функция. Её явно стоит растащить на несколько небольших. К тому же, для вашей функции это сделать с одной стороны просто, а с другой -- необходимо, ибо сам парсинг написан довольно скомкано.

2022-04-09 18:24 UTC, uncerso commented on src/parsing/parse_command_and_arguments.cpp
> +  }
Много логики для одного места. Лучше сделайте функцию аля extractToken, которая вам будет возвращать строку с текущей позиции и до следующего разделителя (пробела, пайпа, конца строки, ...) с учётом наличия кавычек.

Тогда логика будет намного прозрачнее: получить строку и положить в cоmmandStr, получить строку и добавить к аргументам и т.д.

А ещё код, который идёт от открывающейся кавычки до закрывающейся -- тоже надо в отдельную функцию вынести. А заодно там же и кидать исключение (с нормальным описанием), если конец строки достигнут, а закрывающейся кавычки так и не нашлось.

2022-04-09 18:24 UTC, uncerso commented on src/parsing/parse_command_and_arguments.cpp
> +        currArg += line[i];
Не очень хорошая идея к строке добавлять по символу, ибо для неё сложность линейная (а не константа-в-среднем). Лучше использовать `stringstream`.

А ещё лучше не копировать строку вообще, пока не найдёте последний символ токена, и только тогда сделать `substr(начально токена, длина)`. И после рефакторинга этого цикла так сделать будет ничуть не сложнее.

2022-04-09 18:24 UTC, uncerso commented on src/parsing/parse_command_and_arguments.cpp
> +}
`args.erase(std::remove_if(args.begin(), args.end(), std::empty<std::string>), args.end());`

Но вообще, после рефакторинга `for`'a в парсере даже это не нужно будет, ибо на пустую строку можно будет проверять сразу же перед добавлением.

2022-04-09 18:24 UTC, uncerso commented on src/parsing/parse_command_and_arguments.cpp
> +  args = new_args;
Вообще, во всех местах, когда у переменной текущее значение не будет читаться дальше, логично использовать `std::move`, чтобы не копировать лишний раз. Например, здесь `args = std::move(new_args)`, ибо `new_args` дальше не используется. Или ниже `args.push_back(std::move(currArg));`, ибо следующей строкой её значение перетрётся (`currArg = "";`).

2022-04-09 18:24 UTC, uncerso commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "-Wall -Wextra -Werror")
Можно ещё `-Wpedantic` докинуть для некоторой полноты.

2022-04-09 18:24 UTC, uncerso commented on src/parsing/parse_command_and_arguments.cpp
> +  }
Надо бы вынести в отдельную функцию.

2022-04-09 18:24 UTC, uncerso commented on src/parsing/parse_command_and_arguments.cpp
> +      }
А с чего вы взяли, что закрывающаяся кавычка будет? Это однозначный out of bound.

2022-04-09 18:24 UTC, uncerso commented on src/commands/command.hpp
> +struct CommandResponse {
А где комментарии-документация ко всему файлу?

2022-04-09 18:24 UTC, uncerso commented on src/commands/command.cpp
> +  std::ignore = args;
Достаточно опустить имя переменной (т.е. `CommandResponse Pwd::run(const Arguments&)`).

2022-04-09 18:24 UTC, uncerso commented on src/commands/command.cpp
> +  std::string tot_data;
`std::stringstream`, ибо файлы могут быть большие, и копировать всё каждый раз при добавлении в конец строки не круто.

2022-04-09 18:24 UTC, uncerso commented on src/commands/command.cpp
> +  variables_->operator[](args[0]) = args[1];
`(*variables_)[args[0]] = args[1];`

А вообще, ещё надо проверить, что аргументов достаточно. И что лишних нет (сообщать ошибкой пользователю).  Как здесь, так и в остальных командах.

2022-04-09 18:24 UTC, uncerso commented on src/commands/command.cpp
> +  exit(0);
Не классно выходить через `exit`, ибо тогда фиг протестируешь. Но здесь ладно.

2022-04-09 18:24 UTC, uncerso commented on src/parsing/parse_command_and_arguments.cpp
> +  }
Помните про единственность ответственности. Парсер должен парсить. Проверка на существование файлов -- не парсинг. Вот пусть этим `ExternalCommand` занимается.  К тому же, текущая проверка не работает, ибо в `PATH` не ищется, например (а какой-нибудь `git status` работать должен).

2022-04-09 18:24 UTC, uncerso commented on src/commands/command.cpp
> +  auto command = "./" + executable_file_ + " " + utils::join(args, " ");
Прикольно, конечно, добавлять `./` к абсолютному пути, жаль `system` шутки не поймёт.

2022-04-12 20:29 UTC, keygang commented
Merged https://github.com/keygang/yads-bash-software-design/pull/19

2022-04-12 20:36 UTC, keygang commented
PR фазы 2 https://github.com/keygang/yads-bash-software-design/pull/13

2023-07-29 08:57 UTC, merged